gpt-4o-mini:
    import: "./openai-chat.yaml"
    parameters:
        name: "gpt-4o-mini"
        body:
            model: "gpt-4o-mini"
            max_tokens: 512

text-davinci-003:
    import: "./openai-text.yaml"
    parameters:
        name: "text-davinci-003"
        body:
            model: "text-davinci-003"
            max_tokens: 512

text-davinci-002:
    import: "./openai-text.yaml"
    parameters:
        name: "text-davinci-002"
        body:
            model: "text-davinci-002"
            max_tokens: 512

qwen3-chat:
    import: "./qwen-chat.yaml"
    parameters:
        name: "qwen3-vl-30b-a3b-thinking"
        body:
            model: "qwen3-vl-30b-a3b-thinking"
            max_tokens: 512

qwen3-14b-ollama:
  import: "./ollama-qwen.yaml"
  parameters:
    name: "qwen3:14b"
    body:
      model: "qwen3:14b"
      max_tokens: 2048
      temperature: 0
      think: true
      stream: false

qwen3-8b-Thinking-ollama:
  import: "./ollama-qwen.yaml"
  parameters:
    name: "Willem27/Qwen3-VL-8B-Thinking:latest"
    body:
        model: "Willem27/Qwen3-VL-8B-Thinking:latest"
        max_tokens: 512
