module: src.client.agents.HTTPAgent
parameters:
  url: http://127.0.0.1:11434/api/chat   # 🔴 endpoint nativo Ollama
  headers:
    Content-Type: application/json
  body:
    stream: false
    think: true
  prompter:
    name: role_content_dict
    args:
      agent_role: assistant
  return_format: "{response}"