module: src.client.agents.HTTPAgent
parameters:
  name: <% NAME %>
  url: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1/completions"
  headers:
    Content-Type: application/json
    Authorization: Bearer sk-4f3d557a216746bf8ef18c0ce1b3c5bf
  body:
    model: <% NAME %>
    temperature: 0
    enable_thinking: true # added to save reasoning_content
  prompter:
    name: prompt_string
  return_format: "{response[choices][0][text]}"  

